/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informasi.SG;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pungki
 */
public class user_tampil extends javax.swing.JFrame {

    /**
     * Creates new form user_tampil
     */
    public user_tampil() {
        initComponents();
        tampilkan_data();
    }
  private  void tampilkan_data (){
        DefaultTableModel model = new DefaultTableModel ();
        model.addColumn ("ID SG");
        model.addColumn ("Tanggal");
        model.addColumn ("Waktu");
        model.addColumn ("Tempat");
        model.addColumn ("Pemateri");
        model.addColumn ("Kuota Forum");
    
        try { 
            int no = 1;
            String sql = "SELECT * FROM info_sg";
            java.sql.Connection conn = (Connection)konek.konekDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery (sql);
            
            while(res.next()){
            model.addRow(new Object [] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});        
        }
        info_sg.setModel (model);
            
        }catch (SQLException e ){
            System.out.println("ERROR " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        info_sg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        klik_daftar = new javax.swing.JButton();
        klik_unggah = new javax.swing.JButton();
        klik_unduh = new javax.swing.JButton();
        klik_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        info_sg.setBackground(new java.awt.Color(204, 255, 102));
        info_sg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info_sg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        info_sg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID SG", "Tanggal", "Waktu", "Tempat", "Pemateri", "Kuota Forum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        info_sg.setToolTipText("");
        jScrollPane1.setViewportView(info_sg);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 762, 210);

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFORMASI STADIUM GENERAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 470, 37);

        klik_daftar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        klik_daftar.setText("DAFTAR");
        klik_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klik_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(klik_daftar);
        klik_daftar.setBounds(149, 354, 87, 31);

        klik_unggah.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        klik_unggah.setText("UNGGAH");
        klik_unggah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klik_unggahActionPerformed(evt);
            }
        });
        getContentPane().add(klik_unggah);
        klik_unggah.setBounds(254, 354, 95, 31);

        klik_unduh.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        klik_unduh.setText("UNDUH");
        klik_unduh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klik_unduhActionPerformed(evt);
            }
        });
        getContentPane().add(klik_unduh);
        klik_unduh.setBounds(367, 355, 85, 29);

        klik_login.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        klik_login.setText("LOGIN ADM");
        klik_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klik_loginActionPerformed(evt);
            }
        });
        getContentPane().add(klik_login);
        klik_login.setBounds(470, 355, 113, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informasi/SG/screen-1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 870, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void klik_unduhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klik_unduhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klik_unduhActionPerformed

    private void klik_unggahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klik_unggahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klik_unggahActionPerformed

    private void klik_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klik_daftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klik_daftarActionPerformed

    private void klik_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klik_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klik_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_tampil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable info_sg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton klik_daftar;
    private javax.swing.JButton klik_login;
    private javax.swing.JButton klik_unduh;
    private javax.swing.JButton klik_unggah;
    // End of variables declaration//GEN-END:variables
}
